export enum ActionTypes {
    'GET_USER_LIST' = 'GET_USER_LIST',
    'SET_USER_LIST' = 'SET_USER_LIST',
    'IS_DELETE_MODAL_OPEN' = 'IS_DELETE_MODAL_OPEN',
    'REDIRECT_TO_POST_PAGE' = 'REDIRECT_TO_POST_PAGE',
}